# Source: https://focisolutions.com/2020/04/github-actions-deploying-an-angular-app/
name: Deploy To GitHub Pages

on:
  push:
    branches:
      - 'main'
permissions:
  contents: write

jobs:
  build:
    name: Build Angular App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Generate 404.html file
        run: cp www/index.html www/404.html
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: deploy_dir
          path: www
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: deploy_dir
          path: www
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: www
